export const tokens = {
  colors: {
    light: {
      background: '#FFFFFF',
      surface: '#F8FAFC',
      surfaceRaised: '#FFFFFF',
      primary: '#16a34a',
      primaryForeground: '#FFFFFF',
      secondary: '#F1F5F9',
      secondaryForeground: '#0F172A',
      muted: '#F1F5F9',
      mutedForeground: '#64748B',
      destructive: '#DC2626',
      destructiveForeground: '#FFFFFF',
      border: '#E2E8F0',
      input: '#E2E8F0',
      text: '#0F172A',
      textMuted: '#64748B',
      textInverse: '#FFFFFF',
      overlay: 'rgba(0,0,0,0.4)',
      success: '#16a34a',
      warning: '#D97706',
    },
    dark: {
      background: '#09090B',
      surface: '#18181B',
      surfaceRaised: '#27272A',
      primary: '#22c55e',
      primaryForeground: '#052e16',
      secondary: '#27272A',
      secondaryForeground: '#FAFAFA',
      muted: '#27272A',
      mutedForeground: '#A1A1AA',
      destructive: '#ef4444',
      destructiveForeground: '#FEF2F2',
      border: '#3F3F46',
      input: '#3F3F46',
      text: '#FAFAFA',
      textMuted: '#A1A1AA',
      textInverse: '#09090B',
      overlay: 'rgba(0,0,0,0.6)',
      success: '#22c55e',
      warning: '#FBBF24',
    },
  },
  spacing: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    16: 64,
  },
  radius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  typography: {
    h1: { fontSize: 28, fontWeight: '700' as const, lineHeight: 36 },
    h2: { fontSize: 22, fontWeight: '600' as const, lineHeight: 30 },
    h3: { fontSize: 18, fontWeight: '600' as const, lineHeight: 26 },
    body: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22 },
    bodyMd: { fontSize: 15, fontWeight: '500' as const, lineHeight: 22 },
    small: { fontSize: 13, fontWeight: '400' as const, lineHeight: 18 },
    caption: { fontSize: 11, fontWeight: '400' as const, lineHeight: 16 },
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 3,
    },
  },
} as const;

export type ColorScheme = 'light' | 'dark';
export type Colors = typeof tokens.colors.light;
